- name: Application Server Configuration
  hosts: appserver
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install PHP, MySQL client, and Nginx
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php8.3-fpm
        - php-mysql
        - mysql-client
        - nginx

    - name: Ensure apache is stopped
      service:
        name: apache2
        state: stopped

    - name: Enable PHP-FPM handling in Nginx config
      blockinfile:
        path: /etc/nginx/sites-available/default
        marker: "# {mark} ANSIBLE MANAGED BLOCK: PHP-FPM"
        insertafter: "^\\s*index.+$"
        block: |
          location ~ \.php$ {
              include snippets/fastcgi-php.conf;
              fastcgi_pass unix:/run/php/php8.3-fpm.sock;
          }

    - name: Ensure php-fpm is started and enabled
      service:
        name: php8.3-fpm
        state: started
        enabled: yes

    - name: Ensure nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy submit.php to web root
      copy:
        src: ./submit.php
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Copy environment file from Terraform
      copy:
        src: ./db_env.sh
        dest: /etc/profile.d/db_env.sh
        owner: root
        group: root
        mode: '0644'
    
    - name: Upload SQL init script
      copy:
        src: ./sql/init_db.sql
        dest: /tmp/init_db.sql
        mode: '0644'
    
    - name: Run init script on RDS
      shell: |
         source /etc/profile.d/db_env.sh
         mysql -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" < /tmp/init_db.sql
      args:
        executable: /bin/bash

